spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
      username: root
      password: root

  redis:
#    password: root
    host: localhost
    port: 6379
    database: 0

mybatis-plus:
  configuration:
    # 驼峰命名法：将数据库中表名和字段名中的下划线去掉，按照驼峰命名法
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
